### DISCUSSION TITLE
placeholder of ip xxx.xxx.xxx.xxx/28 is calculated as a division

### DISCUSSION THREAD

**Discussion by MalfuncEddie** [ansibleguy76/ansibleforms#128] [Q&A] [answered]
I retreive IP's by rest api in the form of xxx.xxx.xxx.xxx/28 but the placeholder is calculated and cast to int ;(
```
 - name: server_ip_tmp
    type: enum
    label: IP
    expression: fn.fnRestAdvanced( 'get',
      'url','',{}, '[.[]]')
    columns:
      - address
    valueColumn: address
    noOutput: true

  - name: server_ip
    type: expression
    label: IP
    expression: "'$(server_ip_tmp)'.split('/')[0]"
    runLocal: true
    hide: true
```

What am I doing wrong?

some code /headers/url censored
