### DISCUSSION TITLE
How to set a field to integer type?

### DISCUSSION THREAD

**Discussion by slekkus75** [ansibleguy76/ansibleforms#157] [Q&A] [answered]
Hi, I might be missing something obvious, but cannot find the answer in the documentation. 
Passing two field to AWX, which need to be integer, but there is no type: integer. Any clue would be appreciated. 

Fail msg:
 **- Value 2048 for 'vm_hw_ram_mb' expected to be an integer.**
 **- Value 21 for 'vm_disk_gb' expected to be an integer.**

The form:
```
  - name: vm_hw_cpu_n
    label: "Number of CPUs:"
    default: "2"
    type: text
    required: true
  - name: vm_hw_ram_mb
    label: "Memory size in MegaBytes:"
    default: "2048"
    type: text

```

regards.

**Comment by shubhammer** [comment]
did you checked type "number"

**Reply by slekkus75** [reply]
Hi, same error message. 

variables_needed_to_start:
  - Value 2048 for 'vm_hw_ram_mb' expected to be an integer.
  - Value 21 for 'vm_disk_gb' expected to be an integer.



This is the form I use:
```
name: Deploy Debian12 VM
type: awx
template: TMP_TEST_provisionVM_debian12
roles:
  - demo
  - IC-Engineering
description: "This will run an Ansible AWX template, deploying a VM based on the
  configration entered.  "
showHelp: true
help: |
  Test.
icon: cloud-arrow-up
categories:
  - VMWare VM Deployments
tileClass: has-background-success-light
inventory: ""
fields:
  - name: vm_template
    label: "VM template name:"
    default: linux-debian-12.4
    type: text
    required: true
  - name: vm_name
    label: "New VM name (will be set as the local/leaf hostname):"
    type: text
    required: true
    regex:
      expression: ^(?!-)[-a-zA-Z0-9]{1,63}(?<!-)$
      description: Invalid local/leaf hostname..
  - name: vm_net_name
    label: "Network (vlan):"
    type: text
    default: vlan1
    required: true
  - name: vm_ipv4_addr
    label: "IPv4 address:"
    default: 172.16.10.123
    type: text
    required: true
  - name: vm_netmask
    label: "Netmask:"
    default: 255.255.255.0
    type: text
    required: true
  - name: vm_gateway
    label: Gateway
    default: 172.16.10.1
    type: text
    required: true
  - name: vm_dns1_addr
    label: "DNS1 address:"
    placeholder: ""
    default: 172.16.10.10
    type: text
  - name: vm_dns2_addr
    label: "DNS2 address:"
    placeholder: ""
    default: 172.16.10.11
    type: text
  - name: vm_hw_cpu_n
    label: "Number of CPUs:"
    default: "2"
    type: number
    required: true
  - name: vm_hw_ram_mb
    label: "Memory size in MegaBytes:"
    default: "2048"
    type: number
    required: true
  - name: vm_disk_gb
    label: "Disk size in GB (thin provisioned):"
    default: "21"
    type: number
    required: true
  - name: vm_datastore_cluster
    label: "Datastore cluster:"
    default: HyperSwap-DB
    type: text
    required: true
  - name: vcenter_datacenter
    label: "vCenter Datacenter name:"
    type: text
    default: DC
    required: true
  - name: vm_cluster
    label: "Datacenter Cluster name:"
    default: Cluster
    type: text
    required: true
  - name: vm_folder
    label: "Folder the VM should be created in:"
    default: Deploy
    type: text
    required: true
source: prov_vm.yml

```
