### DISCUSSION TITLE
tried using enum field with a mysql as source but complains about server not supporting 'secure connection'.

### DISCUSSION THREAD

**Discussion by slekkus75** [ansibleguy76/ansibleforms#164] [General]
Hi, testing a database source, I added the credentials (left secure connection unchecked), but keep getting below error. 
query error: server does not support secure connection.

If I shell into the af_app container and connect w mysql client, all is well.

**Comment by ansibleguy76** [comment]
I assume you use port 3306 ?

**Comment by slekkus75** [comment]
Port 3309. Test db is a docker container on the same host as the af docker compose

**Reply by ansibleguy76** [reply]
aha... so you are using 2 mysql instances in the same compose.
Can you connect to the 3306 on the config database of ansibleforms ?
most likely root/AnsibleForms!123 ?

**Reply by ansibleguy76** [reply]
can I see the docker-compose file ?

**Reply by slekkus75** [reply]
Credential for the AnsibleForms db server works (port 3307 and database "AnsibleForms"). 
Connecting to my other mariadb db server on port 3309 server errors with no secure connection supported by server. 
Does work when connecting from af_app shell:
`
/app # mysql -u testuser -ptestuser -h 172.16.27.20 -P 3309
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 38
Server version: 11.3.2-MariaDB-1:11.3.2+maria~ubu2204 mariadb.org binary distribution
`

This is docker-compose of the additional db server. 
```
 services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3309:3306"
```


This is AF docker-compose:

```
services:
  # MySql Server
  mysqldb:
    image: mysql:8.1
    container_name: af_db
    restart: unless-stopped
    # load extra environment variables from file
    env_file: ./.env
    # Set manual environment variables
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=AnsibleForms
    ports:
      # Mount host port to docker internal port
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      # Map database location (to maintain persistency)
      - ./data/mysql/db:/var/lib/mysql
      # Map my.cnf file (to maintain persistency)
      - ./data/mysql/my.cnf:/etc/mysql/my.cnf
      # Map init sql scripts
      - ./data/mysql/init:/docker-entrypoint-initdb.d
  # AnsibleForms application
  app:
    # Only start after MySql
    depends_on:
      - mysqldb
    image: ansibleguy/ansibleforms:latest
    container_name: af_app
    restart: unless-stopped
    ports:
      # Mount host port to docker internal port
      - $WEBAPP_LOCAL_PORT:$WEBAPP_DOCKER_PORT
    # Load extra environment variables from file
    env_file:
      - ./.env
    # Set environment variables
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - PORT=$WEBAPP_DOCKER_PORT
      # adding python path to add our custom persistent lib location
      - PYTHONPATH=/usr/lib/python311.zip:/usr/lib/python3.11:/usr/lib/python3.11/lib-dynload:/usr/lib/python3.11/site-packages:/app/dist/persistent/python/lib
    # allow interactive shell
    stdin_open: true
    # allow terminal
    tty: true
    volumes:
      # Mount application folder to host folder (to maintain persistency)
      - ./data:/app/dist/persistent
      # Mount images folder to host folder (to have custom images)
      - ./data/images:/app/dist/views/assets/images
      # Mount logo (to have custom logo)
      #- ./data/images/mylogo.svg:/app/dist/views/assets/img/logo_ansible_forms_full_white.svg
      # Mount background image (to have custom background)
      #- ./data/bg.jpg:/app/dist/views/assets/img/bg.jpg
      # Map custom functions for js expressions and jq
      - ./data/functions/custom.js:/app/dist/src/functions/custom.js
      - ./data/functions/jq.custom.definitions.js:/app/dist/src/functions/jq.custom.definitions.js
      # Map custom sshkey to local node .ssh location
      - ./data/ssh:$HOME_DIR/.ssh
      - ./data/git/.gitconfig:$HOME_DIR/.gitconfig
      # Map custom ansible.cfg
      - ./data/ansible/ansible.cfg:/etc/ansible/ansible.cfg
      - ./data/ansible/roles:/etc/ansible/roles
      - ./data/ansible/collections:/etc/ansible/collections
```
`
docker ps:

```
CONTAINER ID   IMAGE                            COMMAND                  CREATED        STATUS        PORTS                                                  NAMES
0b1e67f12539   mariadb                          "docker-entrypoint.s…"   19 hours ago   Up 19 hours   0.0.0.0:3309->3306/tcp, :::3309->3306/tcp              compan-mariadb_db_1
d8a0bf9a13ec   ansibleguy/ansibleforms:latest   "node ./dist/index.js"   6 days ago     Up 6 days     0.0.0.0:8443->8443/tcp, :::8443->8443/tcp              af_app
92d109728c88   mysql:8.1                        "docker-entrypoint.s…"   6 days ago     Up 6 days     33060/tcp, 0.0.0.0:3307->3306/tcp, :::3307->3306/tcp   af_db
```
