### DISCUSSION TITLE
New in version 5.0.2

### DISCUSSION THREAD

**Discussion by ansibleguy76** [ansibleguy76/ansibleforms#183] [Announcements]
### Adding
-   Now allowing string (credential name) or array (of names) as dbConfig (dbtype is fetched from the database, with mysql fallback)
    When using array, the resultsets are merged.
-   Added ytt implementation to template yaml files (credits mdaugs)
-   Vault credentials, pass a vault password to ansible playbook.
-   OIDC authentication (credits mdaugs)
-   Ansibleforms will now wait for mysql to be ready before initializing
-   awx job id is added to the database- 

### Changed

-   job api return objects (extravars, notifications, credentials, ...) instead of json strings

### Fixed

-   radio button errors
-   some issue with the designer when a field without name was added
-   multistep was always successfull (tx to mdaugs)
-   using cookie session instead express session

**Comment by mahjatech** [comment]
Hi!

in Cli it works:

```shell
echo "R3Jl********************QAo=" | base64 -d | ansible-playbook -e 'numachine=99999' -i inventory.y
ml demarrage.yml --vault-password-file=/bin/cat
```

#-----------------------------------------
but in form, it doesn't work:
```yaml
name: Démarrage machine
showHelp: true
help: |
  Projet Démarrage de d'une machine
roles:
  - public
description: This workflow start a machine.
categories:
  - Ansible
tileClass: has-background-warning-light
# vaultCredentials: __vaultCredentials__
playbook: demarrage.yml
inventory: inventory.yml
verbose: true
type: ansible
fields:
  - name: numachine
    type: number
    label: Numéro de machine
  - name: __vaultCredentials__
    type: password
    label: vault password
```

**Reply by mahjatech** [reply]
Can you put an example of its use ?

**Reply by ansibleguy76** [reply]
You add credentials to AF.  

![image](https://github.com/ansibleguy76/ansibleforms/assets/89778474/7e1ff777-0ca5-4827-8af4-567f08ba70a6)

(in my case "vault")

Then you set the vaultCredentials property to the name of the credential:

```
name: New Form
type: ansible
playbook: dummy.yaml
description: ""
roles:
  - public
categories: []
vaultCredentials: vault
tileClass: has-background-info-light
icon: bullseye
fields:
  - name: field1
    type: text
    label: field1

```

**Reply by ansibleguy76** [reply]
Or you can use the field to make it dynamic => make sure the fields value is the name of the vault

```
name: New Form
type: ansible
playbook: dummy.yaml
description: ""
roles:
  - public
categories: []
tileClass: has-background-info-light
icon: bullseye
fields:
  - name: __vaultCredentials__
    type: text
    default: vault
```
