### DISCUSSION TITLE
How to pass credentials to a playbook deploying VMWare VMs

### DISCUSSION THREAD

**Discussion by slekkus75** [ansibleguy76/ansibleforms#195] [Q&A] [answered]
Hi, cannot find on how to pass the credentials to a playbook. Using this collection: https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html
I added a (non-db) cred under credentials, but this is a key based value. What does it pass? Or should I do:
vccenter_host = cred.url
vccenter_uname = cred.name
vccenter_upass = cred.pass

regards..

**Comment by ansibleguy76** [comment]
what exactly is not working?

you can pass the stored credentials in several ways.  with the form property "credentials" or with a field called ____credentials____ or by adding "asCredential" property to a field. each time you pass the name of the credentials and they will be injected as a dict with all properties like user, password.  the password is encrypted in the database.  make a simple playbook and debug the credentials object to see all the properties.

**Reply by slekkus75** [reply]
I clearly have no clue. I tried this:


credtestform.yml

```
name: Test passing credentials
type: ansible
playbook: credtest.yaml

roles:
  - admin
description: Testing credentials
icon: trash
categories:
  - VMWare VM Deployments

inventory: ""
credentials:
  testcred: testcredvar

fields:
  - type: checkbox
    name: placeholder
    default: false 
```


credtest.yaml:

```
- name: Get creds
  hosts: localhost
  gather_facts: true

  tasks:

  - name: "Get the command line args"
    shell: "cat -A /proc/{{ lookup('pipe', 'echo $PPID') }}/cmdline |sed -r 's/\\^@/ /g'"
    register: cmd_line
    delegate_to: localhost

  - name: "Print the arguments passed to the playbook"
    debug:
      msg: "{{ cmd_line.stdout.split(' ')|select() }}"
```

credentials:
![2024-07-04 11_40_42-Ansible Forms and 6 more pages - Work - Microsoft​ Edge](https://github.com/ansibleguy76/ansibleforms/assets/157806656/2990522e-6204-4ca6-984e-aaf60d36d47a)

Result:
![2024-07-04 12_51_32-Ansible Forms and 6 more pages - Work - Microsoft​ Edge](https://github.com/ansibleguy76/ansibleforms/assets/157806656/d908ddfb-655b-4a7a-b1d8-56517413503e)
