### DISCUSSION TITLE
How prevent values duplication in table ?

### DISCUSSION THREAD

**Discussion by ansibleguy77** [ansibleguy76/ansibleforms#196] [Q&A] [answered]
How to remove a value from the tablefields if it has been added to the table or marque a field Machine unique to prevent values duplication ?
```
fields:
  - type: table
    name: mach
    label: Ajouter une mach
    allowInsert: true
    allowDelete: true
    insertMarker: isNewItem
    deleteMarker: isRemovedItem
    readonlyColumns:
      - Machine
      - hostname
    required: true
    tableFields:
      - type: enum
        name: Machine
        label: Machine
        values:
          - mach1
          - mach2
          - mach3
          - mach4
        icon: user
      - type: enum
        name: hostname
        label: Hostname
        values:
          - patlb01
          - patlb02
          - patlb03
          - patlb04
      - name: Selected
        label: Selected
        placeholder: selectionner
        type: checkbox
        required: true
        default: true
```

**Comment by ansibleguy76** [comment]
you can add a hidden expression field where you analyse the table data to a true / false and then use that field as validation on the table

**Reply by ansibleguy77** [reply]
It's too complicated. 
We need a specific property or parameter for dynamic management fields for  input form like a primary key in Mysql.

**Reply by ansibleguy76** [reply]
can you make an issue and describe the specific feature in detail?

i will then put it on the todolist

**Reply by ansibleguy76** [reply]
meanwhile

```
name: nodoubles
type: expression
runLocal: true
expression: fnArray.from($(mach)).distinctBy('uniquefield').length==$(mach).length

name: mach
validIfNot:
  field: nodoubles
  description: you cannot have doubles, uniquefield must be unique
type: table
```

**Reply by ansibleguy76** [reply]
it's typed on my phone on a beach. so i can't test it, but should be close.  the expression nodoubles will be false if a double is found (uniquefield in my example)

the table will show the error if nodoubles is false

**Reply by ansibleguy77** [reply]
I know "expression" is wrong but it's just to make myself understood
```
fields:
  - type: table
    name: mach
    label: Ajouter une mach
    allowInsert: true
    allowDelete: true
    insertMarker: isNewItem
    deleteMarker: isRemovedItem
    readonlyColumns:
      - Machine
      - hostname
    required: true
    tableFields:
      - name: Machine
        type: enum
        expression: |
          $mach ? ['mach1','mach2','mach3','mach4'].filter(x => !$mach.some(m => m.Machine === x)) : ['mach1','mach2','mach3','mach4']
          # with a javascript expression
        runLocal: true
```
![ansibleforms_1](https://github.com/ansibleguy76/ansibleforms/assets/174320404/9a07c432-b114-4366-8574-32fd480faa30)
![ansibleforms_2](https://github.com/ansibleguy76/ansibleforms/assets/174320404/6695190d-76cc-40e2-96ad-fee9f9968a0c)

**Reply by ansibleguy77** [reply]
Sorry I didn't see your last reply

**Reply by ansibleguy77** [reply]
I have : 
Form warnings

'nodoubles' has query errors
TypeError: Cannot read properties of undefined (reading 'split')

![ansibleforms_3](https://github.com/ansibleguy76/ansibleforms/assets/174320404/d1cada94-4322-47b8-9dd3-953768e68373)

**Reply by ansibleguy76** [reply]
can you explain in detail what it is you try to reach.  not how you try to do it, what you want and i will see if i can make you a sample.

**Comment by ansibleguy76** [comment, marked as answer]
I believe this is what you want.  I used several expressions for ease of reading, but you can merge them if you want.  
Don't worry about speed, all the expressions are run local, so speed will be okay.
Let's go over the steps

First I define a list `machineList` (with an expression) => you could load this from rest, from a file, ...
This holds our list of machines.

Then I make 2 expressions : one making a list of the ones in your table (usedMachinelist), and then the ones not yet picked in the table (unusedMachinelist) => by substracting the used ones from the list.

We make a table field `machines`

![image](https://github.com/ansibleguy76/ansibleforms/assets/89778474/6bdb4723-8ba0-4f5c-a1bb-2d9f2dc235c3)


The table field machine uses the `from `property to use a dropdown list from an outside epxression (the unsedMachinelist).
Each time you pick a new machine, the list gets reduced, not allowing you to pick the same machine twice.

![image](https://github.com/ansibleguy76/ansibleforms/assets/89778474/281e5978-0d07-422c-bb60-8edc3e862e95)

![image](https://github.com/ansibleguy76/ansibleforms/assets/89778474/a32daae8-7de7-4f20-855c-126cea96861c)

But let's go a little further.  Let's assume you have manual input, you also want to be unique.
It have added a second field "Id" to the table

Another 2 expressions `idList` and `hasIdDoubles` will help use check if the id is unique in our table.
Using the `validIfNot` validation, we now show an error that the id must be unique.

![image](https://github.com/ansibleguy76/ansibleforms/assets/89778474/eeaa5603-cc63-4fb6-85c5-e8b00c30bd88)

Greetings from Ibiza :)

```
name: Table unique
type: ansible
playbook: dummy.yaml
description: ""
roles:
  - public
categories: []
tileClass: has-background-info-light
icon: bullseye
fields:
  - name: machinelist
    type: expression
    value:
    - mach1
    - mach2
    - mach3
    - mach4
  - name: usedMachinelist
    type: expression
    runLocal: true
    expression: $(machines).map(x => x.Machine)
  - name: unusedMachinelist
    type: expression
    runLocal: true
    expression: $(machinelist).filter( x => !$(usedMachinelist).includes(x))
  - type: table
    name: machines
    label: Add a machine
    allowInsert: true
    allowDelete: true
    insertMarker: isNewItem
    deleteMarker: isRemovedItem
    validIfNot:
      field: hasIdDoubles
      description: This table must have unique id's
    readonlyColumns:
      - Machine
      - hostname
    required: true
    tableFields:
      - name: Machine
        label: pick a machine
        type: enum
        required: true
        from: unusedMachinelist
      - name: Id
        label: Give a unique id
        type: text
        required: true
  - name: idList
    type: expression
    runLocal: true
    expression: $(machines).map(x => x.Id)
  - name: hasIdDoubles
    type: expression
    runLocal: true
    expression: "((x) => new Set(x).size !== x.length)($(idList))"
    
```
