### DISCUSSION TITLE
Need help with dynamic inventory. Can't figure out how to use (in general).

### DISCUSSION THREAD

**Discussion by slekkus75** [ansibleguy76/ansibleforms#237] [Q&A]
Hi, have been fiddling around this morning run playbooks against a dynamically generated inventory. I think, I need a multistep form for this, but before I figure that out, I do not see how get the plugin to work. 
It is the following plugin I would like to use: https://github.com/freeipa/ansible-freeipa/blob/master/plugins/inventory/freeipa.py

So installed the "anwsible-freeipa" collection using the maintenance forms included with ansibleforms, that succeeded and can find the plugin . But how do I generate the inventory and pass this to a subsequent playbook? 

multistep form:

```
name: "Update Linux Servers"

roles:
  - admin
  
credentials:
  idmacreds: idm_admin
  
type: multistep
steps:
- type: ansible
  name: "Generate Inventory"
  playbook: linuxupdates_geninv.yaml
  key: linuxupdates_inventory

- type: ansible
  name: "Update Linux VMs"
  playbook: updatelinux.yaml
  inventory: linuxupdates_inventory

categories:
  - LinuxUpdate

fields:
  - name: dummy
    type: dummy
```

linuxupdates_geninv.yaml:

```
plugin: freeipa
server: server
ipaadmin_password: {{ idmacreds.password }} 
verify: ca.crt
```
 
Also added enable_plugins setting in ansible.cfg:

```
[defaults]
stdout_callback = yaml
COLLECTIONS_PATHS=/usr/share/ansible/collections/ansible_collections:/etc/ansible/collections/ansible_collections
host_key_checking = False
enable_plugins=freeipa

```
