### DISCUSSION TITLE
Usage of model variable instead of name in expressions.

### DISCUSSION THREAD

**Discussion by nikos445** [ansibleguy76/ansibleforms#253] [Q&A] [answered]
Is there a way to use "Model" variable instead of "Name" in expressions?

I am trying to do something like this:

- type: enum
  name: choice
  values:
   - x
   - y

- type: expression
   name: x
   model: test
   expression: '{x: "123"}'
   dependencies: x

- type: expression
   name: y
   model: test
   expression: '{x: "456"}'
   dependencies: y

- type: expression
   name: z
   expression: "return 'test.x' "

where x and y is 2 Remote API requests and "z" is a local option after one of requests return a value...

Any ideas?

**name: z**   shall be the same always as it is used by multiple other expressions ...

**Comment by ansibleguy76** [comment]
```
name: New Form
type: ansible
playbook: dummy.yaml
description: ""
roles:
  - public
categories: []
tileClass: has-background-info-light
icon: bullseye
fields:
  - name: select
    type: enum
    values:
    - x
    - y
  - name: x
    type: expression
    runLocal: true
    value:
      x: 123
    dependencies:
    - name: select
      values:
      - x
  - name: y
    type: expression
    runLocal: true
    value:
      x: 456
    dependencies:
    - name: select
      values:
      - y      
  - name: z
    type: expression
    runLocal: true
    ignoreIncomplete: true
    expression: ((i)=>{return `you selected ${i.x}`})($(x) || $(y))
source: helloworld.yaml

```
