### DISCUSSION TITLE
How can I populate a host field based on a user's role ?

### DISCUSSION THREAD

**Discussion by le-martre** [ansibleguy76/ansibleforms#255] [Q&A] [answered]
Hello ! 

My use case is relatively simple : host groups should only be available to people with the right "role" in ansibleforms.
I tried using an expression which seemed perfect but there is a limit to the number of instructions you can send in the backend and I cannot do RBAC in the front-end obviously. I checked in the code but there doesn't seem to be a way to remove that limitation.

Is there maybe some other way to do that ? Otherwise I will build a custom verison of the app, no worries ! 

Example of what I'd like to do roughly : 

```
expression: |
        let hosts = [];
        let groups = [];

        if (user.roles.includes('admin')) {
          hosts = inventory.hosts.map(host => host.name);
        } else {
          if(user.roles.includes('role1')) groups.push('role1');
          if(user.roles.includes('role2')) groups.push('role2');

          if(groups.length()) {
            hosts = inventory.groups[groups].hosts.map(host => host.name);
          }

          return hosts:
        };
```

Thanks for the great tool !

**Comment by ansibleguy76** [comment]
Add runLocal: true

**Reply by ansibleguy76** [reply]
backend expressions are sanitize for security

**Reply by ansibleguy76** [reply]
ps : wait 5 minutes for example

**Comment by ansibleguy76** [comment]
```
name: Role selection
type: ansible
playbook: dummy.yaml
description: ""
roles:
  - public
categories: []
tileClass: has-background-info-light
icon: bullseye
fields:
  - name: hosts
    type: expression
    value:
    - host: foobar
      role: admin
    - host: pingpong
      role: public
    - host: noaccess
      role: operator
  - name: host
    type: enum
    expression: "$(hosts).filter(x => $(__user__.roles).includes(x.role))"
    runLocal: true
source: helloworld.yaml
```
