### DISCUSSION TITLE
How to rewrite ENUM selected values with seperate expression.

### DISCUSSION THREAD

**Discussion by JamesHutchinsonHV** [ansibleguy76/ansibleforms#265] [Q&A] [answered]
I have an enum that obtains its list or from at API using fnRestBasic. 

My selections in the main form are stored as portPairs

```
  - name: portPairs
    label: Port Pairs
    type: enum
    required: true
    expression: fn.fnRestBasic('get','http://172.16.169.116//storage_array/$(array.serial_number)/portpairs?hostType=any&hostType=$(hostType.name)','','')
    horizontal: false
    multiple: true
    outputObject: true
    sticky: true
```

This results in the following in extravars, if multiple portPairs are selected:
![image](https://github.com/user-attachments/assets/8a91459b-8547-477e-9c93-de883675a827)

```
"portPairs":[
{
"hostType":"ANY",
"primaryPort":"CL1-C",
"secondaryPort":"CL2-C"
},
{
"hostType":"Windows",
"primaryPort":"CL1-A",
"secondaryPort":"CL2-A"
}
],
```

I want to flatten this in to a list of ports, for example: ["CL1-C","CL2-C","CL1-A","CL2-A"] so I can use it in a table. 
And to do this I was looking to use a separate expression in the main form and use "from" in the table enum. 

However when I try initially to get the data in to a new variable (portList) via the expression I only get the following:

```
  - name: portList
    type: expression
    expression: $(portPairs)
    runLocal: false
```
Returns:
![image](https://github.com/user-attachments/assets/9b8dc4fe-2f46-4cb0-8f09-65b77bde6dae)

```
[
"ANY",
"Windows"
]
```

I know (portPairs) is an object as per the extravars because if I use this in my table enum the structure with hostType, primaryPort & secondaryPort is shown. but when I view the data in the main form via (portList) I only see a list of hostType's.

```
  - name: serverPaths
    label: Server WWN Mapping
    type: table
    required: true
    dependencies:
      - name: portPairs
        isValid: true
    tableFields:
      - name: serverWWPN
        label: Server WWPN
        type: text
      - name: storagePort
        label: Storage Port
        type: enum
        from: **portPairs**
```
![image](https://github.com/user-attachments/assets/092f7160-c9f0-4e24-b6cc-e9b782e1bb92)

What am I doing wrong?

**Comment by ansibleguy76** [comment]
So you want a single table with port 1 & port 2 and this multiple ?

**Comment by ansibleguy76** [comment]
you can do this with jq 

`expression: fn.fnJq($(portPairs),'[.[] | .primaryPort,.secondaryPort]')`

**Reply by JamesHutchinsonHV** [reply]
With this I just end up with "null" for my (portList)

**Reply by ansibleguy76** [reply]
```
fields:
  - name: portPairs
    type: enum
    outputObject: true
    values:
      - hostType: ANY
        primaryPort: CL1-C
        secondaryPort: CL2-C
      - hostType: Windows
        primaryPort: CL1-A
        secondaryPort: CL2-A
    multiple: true
    placeholderColumn: "*"
    sticky: true
  - name: flat
    type: expression
    expression: fn.fnJq($(portPairs),'[.[] | .primaryPort,.secondaryPort]')
```

![{E4284E06-F72E-427B-8232-C2A8FD2452F9}](https://github.com/user-attachments/assets/37a883e9-5340-43a2-bcd3-71f65161adbc)

**Reply by ansibleguy76** [reply]
note the `fn.fnJq()` is a remote expression, not a local one.  It uses the predefined function fnJq, which otherwise does not exist natively in Javascript.

**Comment by ansibleguy76** [comment]
or you can do it with local javascript

```
runLocal: true
expression: $(portPairs).flatMap(({ primaryPort, secondaryPort }) => [primaryPort, secondaryPort])
```

**Reply by JamesHutchinsonHV** [reply]
```
  - name: portList
    type: expression
    runLocal: true
    expression: $(portPairs).flatMap(({ primaryPort, secondaryPort }) => [primaryPort, secondaryPort])
```

Result:
![image](https://github.com/user-attachments/assets/228004bd-0337-4ef4-b0b7-f0ac511a39df)

**Reply by JamesHutchinsonHV** [reply]
I did intend to use this, but that's when I found that (portPairs) was not structured correctly. 

The log also only shows:
2025-03-14 14:28:11:2811 info: Expression: ["ANY","Windows"]

**Comment by JamesHutchinsonHV** [comment]
My goal is to have a table where I can select from the portList dropdown and add a server MAC resulting in the following If I was to add mac to every port, one at a time via the table. 

"serverPaths":[
{
"port":"CL1-C",
"mac":"xxxxxxx"
},
{
"port":"CL2-C",
"mac":"yyyyyyy"
},
{
"port":"CL1-A",
"mac":"zzzzzzzz"
},
{
"port":"CL2-A",
"mac":"fffffffffff"
}
]

**Comment by ansibleguy76** [comment]
```
fields:
  - name: portPairs
    type: enum
    outputObject: true
    values:
    - hostType: ANY
      primaryPort: CL1-C
      secondaryPort: CL2-C
    - hostType: Windows
      primaryPort: CL1-A
      secondaryPort: CL2-A
    multiple: true  
    placeholderColumn: "*"
  - name: flat
    type: expression
    runLocal: true
    expression: $(portPairs).flatMap(({ primaryPort, secondaryPort }) => [primaryPort, secondaryPort])
```

**Comment by ansibleguy76** [comment, marked as answer]
note the placeholderColumn: "*" => is required to expose all properties

**Reply by JamesHutchinsonHV** [reply]
Spot on that works, Thanks

**Comment by ansibleguy76** [comment]
![{BFADC881-E1B8-40DD-A2F2-5BEF59F66F5E}](https://github.com/user-attachments/assets/a65c61bc-f8b5-45fb-bcdc-5fbc2912c721)

**Comment by ansibleguy76** [comment]
```
fields:
  - name: portPairs
    type: enum
    outputObject: true
    values:
    - hostType: ANY
      primaryPort: CL1-C
      secondaryPort: CL2-C
    - hostType: Windows
      primaryPort: CL1-A
      secondaryPort: CL2-A
    multiple: true  
    placeholderColumn: "*"
  - name: flat
    type: expression
    runLocal: true
    expression: $(portPairs).flatMap(({ primaryPort, secondaryPort }) => [primaryPort, secondaryPort])
  - name: serverPaths
    label: Server WWN Mapping
    type: table
    required: true
    dependencies:
      - name: portPairs
        isValid: true
    tableFields:
      - name: serverWWPN
        label: Server WWPN
        type: text
      - name: storagePort
        label: Storage Port
        type: enum
        from: flat   
```
