### DISCUSSION TITLE
How to avoid double using the table field

### DISCUSSION THREAD

**Discussion by ansibleguy76** [ansibleguy76/ansibleforms#268] [Q&A] [answered]
When using a tablefield, you sometimes want to avoid doubles based on a certain tablefield.  How do you do that

**Comment by ansibleguy76** [comment, marked as answer]
```
fields:
  - name: machinelist
    type: expression
    value:
      - mach1
      - mach2
      - mach3
      - mach4
  - name: usedMachinelist
    type: expression
    runLocal: true
    expression: $(machines).map(x => x.Machine)
  - name: unusedMachinelist
    type: expression
    runLocal: true
    expression: $(machinelist).filter( x => !$(usedMachinelist).includes(x))
  - type: table
    name: machines
    label: Add a machine
    allowInsert: true
    allowDelete: true
    insertMarker: isNewItem
    deleteMarker: isRemovedItem
    validIfNot:
      field: hasIdDoubles
      description: This table must have unique id's
    readonlyColumns:
      - Machine
      - hostname
    required: true
    tableFields:
      - name: Machine
        label: pick a machine
        type: enum
        required: true
        from: unusedMachinelist
      - name: Id
        label: Give a unique id
        type: text
        required: true
  - name: idList
    type: expression
    runLocal: true
    expression: $(machines).map(x => x.Id)
  - name: hasIdDoubles
    type: expression
    runLocal: true
    expression: ((x) => new Set(x).size !== x.length)($(idList))
```
