### DISCUSSION TITLE
How to do dynamic maxValue Expressions in AnsibleForms

### DISCUSSION THREAD

**Discussion by MarcosLealSierra** [ansibleguy76/ansibleforms#269] [Q&A] [answered]
Hello,

I’m currently working with AnsibleForms and have encountered a scenario where a dynamic validation would be extremely helpful. In my form, I need to ensure that a number field does not exceed a limit that is dynamically calculated based on another field’s value. However, it seems that the maxValue property currently only accepts a literal integer and does not support dynamic expressions.

Would it be possible to consider adding support for dynamic validations or custom validators in future versions of AnsibleForms? This feature would greatly assist in scenarios where validation needs to depend on other field values.

Thank you very much for all the hard work on this project. I truly appreciate the effort that has gone into developing AnsibleForms, and I look forward to your thoughts on this suggestion.

Best regards,

Marcos

**Comment by ansibleguy76** [comment]
just make a local expression field that results in a boolean and use the `validIf` or `validIfNot` validator with custom description.

See example : https://github.com/ansibleguy76/ansibleforms/discussions/268

**Comment by ansibleguy76** [comment, marked as answer]
```
fields:
  - name: mymax
    type: number
    default: 5
  - name: ishigher
    type: expression
    runLocal: true
    expression: ((x,y)=>{ return y>x })($(mymax),$(myvalue))
  - name: myvalue
    type: number
    validIfNot:
      field: ishigher
      description: that's too high.
    default: 3
```
