### DISCUSSION TITLE
Problem with Ansible Form when reading JSON file in the form

### DISCUSSION THREAD

**Discussion by jtordesillasmt** [ansibleguy76/ansibleforms#271] [Q&A] [answered]
Hello everyone, I am trying to load a dropdown list in an Ansible form using data from a JSON file, but it keeps loading and doesn’t work. I would appreciate any help.

I have this JSON file:

```json
[
  { "id": 1, "name": "Ana", "department": "Sales" },
  { "id": 2, "name": "Luis", "department": "Marketing" },
  { "id": 3, "name": "María", "department": "Sales" }
]
```

And this form:

```yaml
name: Read JSON
type: ansible
playbook: leer.yaml
roles:
  - admin
categories:
  - Fedora
tileClass: has-background-info-light
icon: spider
fields:
  - type: enum
    name: empleados
    label: Employee List
    expression: fn.fnReadJsonFile('empleados.json','.[].name')
    runLocal: true
source: Fedora.yaml
```

The Ansible playbook looks like this:

```yaml
---
- name: Process form data
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Show selected employee
      debug:
        msg: "Selected employee: {{ empleados }}"
```

The problem is that the form keeps loading with this error in the logs:

```
Form warnings
'empleados' has query errors
ReferenceError: fn is not defined
```
![image](https://github.com/user-attachments/assets/19f74023-5832-41a9-b947-59112aacc723)

I’ve already checked that the JSON file path is correct, but I don’t understand what’s causing this error.

Additionally, I tried testing the **Pet Store API** using `fn.fnRestBasic`, but it doesn’t work either. I’d like to understand how to use it properly.

Has anyone managed to make something like this work? Thanks in advance!

**Comment by ansibleguy76** [comment]
remove runLocal.  
and your jq is wrong too. 
wrap it in additional square brackets

**Reply by jtordesillasmt** [reply]
Thank you for your reply. I’ve tried making the changes you suggested, but I’m still having issues.

- If I remove `runLocal: true`, the form can’t find the `empleados.json` file and keeps showing an error saying it can't access it. It seems that without running locally, it can't access the file in the configured location.

- Regarding the expression, when I change it to `expression: fn.fnReadJsonFile('empleados.json', '.[] | .name')`, it now shows "No data" in the dropdown, indicating that it either can’t find the file or can’t read the data properly. The path to the JSON file is correct, though.

Do you have any ideas on how to fix this? Maybe there’s something else I need to configure for it to work properly.

![image](https://github.com/user-attachments/assets/23053257-bfff-4fff-a955-0263aa65832f)

**Reply by ansibleguy76** [reply]
do you run this in a container?

do you have a persistent folder mapped to you container?

if you used docker compose the path to your persistent folder is likely : /app/dist/persistent.   this will be your mapped data folder. 

you can try fn.fnSsh('<yourcommamd>')

with ls and pwd you will dind the correct path to your file

**Comment by ansibleguy76** [comment]
api calls and reading files are backend actions.  not frontend

**Reply by jtordesillasmt** [reply]
So, does that mean it's not possible to display the JSON data in that enum field? If API calls and file reading should be backend actions and not frontend, how could I load the data from the JSON file into the form?

**Reply by ansibleguy76** [reply]
of course that is possible.  but the json file is your linux server, right?  fn.fnReadYamlFile
or fn.fnReadJsonFile are functions that are evaluated on the backend, thus the linux server.  now if you set this up with docker compose, you probably mapped a data folder to /app/dist/persistent.  so that is the absolute path of your data folder.  if you stored the json file somewhere in that data folder you can read it and use it for enum fields.  shall i make a quick example?

**Reply by jtordesillasmt** [reply]
yes please, i mounted it on the fedora machine in docker but i didn't map a data folder to /app/dist/persistent or so i think. i didn't do any of that. i just installed it.

**Reply by ansibleguy76** [reply]
you "just installed this".  can you explain?  you generally don't install ansible forms. you deploy it as a container or you compile and run it with nodejs. 

can you use expression fn.fnSsh('ls /app/dist/persistent/') as a field?

what is the result?

**Reply by jtordesillasmt** [reply]
It shows something like this, but I’m not sure where to execute it. If I run it in the form, I would have to include a playbook, which will result in an error.
[root@node ansibleforms-docker]# fn.fnSsh('ls /app/dist/persistent/')
bash: error sintáctico cerca del elemento inesperado `'ls /app/dist/persistent/''


 I didn't have the `/app/dist/persistent/` folders, but I created them and added the files, and it still can't find the file.
 
![image](https://github.com/user-attachments/assets/ce630ff0-88e4-44fd-8f8b-c7ae8993a567)

  I went into the folder `/home/ansibleforms/ansibleforms-docker/k8s/server-deployment.yaml` and saw the following lines:

```yaml
volumeMounts: 
  - mountPath: /app/dist/persistent
    name: server-persistent-storage
```

I followed the Ansible installation in Docker/Docker Compose in Fedora, exactly as it is, the only thing I changed was the password to access the Ansible form.
https://ansibleforms.com/installation/

**Reply by ansibleguy76** [reply, marked as answer]
ok... here we go

In my docker compose, I map a local folder to the persistent directory of the container.
This way, playbooks, forms, database => all consistent in case the container is recreated.
![{FE085B93-8C60-47D5-8893-8722969E9789}](https://github.com/user-attachments/assets/fd298397-c2a9-4772-b781-04b975869dfd)

In my local data folder (mounted to the container):
![{6351964D-8D36-4A4A-9018-72373C884342}](https://github.com/user-attachments/assets/f472789f-1e42-4177-817e-29270ec8e848)

When I go into my container, I find the exact same files:
![{B14362CF-51A8-4A43-8E74-5FDE2EF3DF56}](https://github.com/user-attachments/assets/108dc42f-7117-4581-bc32-bca3e67b02a3)

Of which my json file
![{F76634CB-E143-4587-A006-6E7B2A9E647A}](https://github.com/user-attachments/assets/086682d9-89fd-4130-9d30-12e6bb94e2b0)

Now let's use the file, consider this field in the form
```
fields:
  - name: test
    type: enum
    expression: fn.fnReadJsonFile('/app/dist/persistent/files/sample.json')
```
![{D03786D0-E9E5-4A5F-A62C-19A7FF27EB6B}](https://github.com/user-attachments/assets/5b2ea305-2434-48f1-ab5e-e054983f9bd7)

Let's filter it with jq (although, you can just use the property `columns`

```
fields:
  - name: test
    type: enum
    expression: fn.fnReadJsonFile('/app/dist/persistent/files/sample.json','[.[]|.name]')
```
![{0A942FAD-513E-4A5A-B0ED-3248B6CCE575}](https://github.com/user-attachments/assets/a669f0bb-e76b-4cad-8c2e-172453f032f4)
