### DISCUSSION TITLE
How to add a static table as information

### DISCUSSION THREAD

**Discussion by vailenwallaces** [ansibleguy76/ansibleforms#294] [Q&A] [answered]
Hello, 

I want to give the user an overview before they, for example, order new accounts.
I have the data that I want to display in a variable:

`data : "[{"name":"ich@hallo.de","type":"SuperAdmin"},{"name":"ich1@hallo.de","type":"NichtsoSuperAdmin"},{"name":"ich2@hallo.de","type":"NichtsoSuperAdmin"}])"`

I tried solving this using a table.

```
- type: table
  name: superaccount
  expression: "$(data)"
  label: "Here are your Admin Accounts"
  allowInsert: false
  allowDelete: false
  readonlyColumns:
     - name
     - type
  tableFields:
     - name: name
        type: text
        icon: user
        label: Login Name
     - name: type
       type: text
       label: Account Type
   noOutput: true
   

```
  
 Is there possibly a better way?
Or is there perhaps an option to hide the Action column?

I understand that "table" is not really intended for this purpose. I played around a bit with "html," but I couldn't quite get it to work.

Or are there other ways? Did I miss something?

thx
