### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by marcelvanheemst** [ansibleguy76/ansibleforms#1]
Within Ansible Forms we can only use Basic Authentication. For usage of other products within Ansible Forms I need Bearer + token based authentication also.

**Comment by ansibleguy76** [comment]
new functions have been added :
fn.fnRestJwt(method,uri,body,token,jq,sort,map) => will add the token as Bearer + token authoration header
fn.fnRestAdvanced(method,uri,body,headers,jq,sort,map) => allows custom headers

```
    fields:
      - type: expression
        name: ansibleformsUri
        label: AnsibleForms Uri
        group: Example connect loopback
        expression: "'http://172.16.50.1:3000'"
      - type: expression
        name: token
        label: Token
        group: Example connect loopback
        expression: fn.fnRestBasic('post','$(ansibleformsUri)/api/v1/auth/login','','AF','.token')
      - type: expression
        name: whoami
        label: Who am i
        group: Example connect loopback
        expression: fn.fnRestJwt('get','$(ansibleformsUri)/api/v1/profile','','$(token)','.data.output.username')
      - type: query
        name: myroles
        label: My roles
        default: __auto__
        group: Example connect loopback
        expression: fn.fnRestJwt('get','$(ansibleformsUri)/api/v1/profile','','$(token)','.data.output.roles')
      - type: expression
        name: vcenterUri
        label: Vcenter URI
        group: Example connect vcenter
        expression: "'https://jabba.slash.local'"
      - type: expression
        name: vcentersession
        label: Vcenter session
        group: Example connect vcenter
        expression: fn.fnRestBasic('post','$(vcenterUri)/rest/com/vmware/cis/session','','VCENTER','.value')
      - type: query
        name: vms
        label: Virtual machines
        group: Example connect vcenter
        expression: fn.fnRestAdvanced('get','$(vcenterUri)/rest/vcenter/vm','',{'vmware-api-session-id':'$(vcentersession)'},'.value')
        default: __auto__
        columns:
          - name
          - cpu_count
          - memory_size_MiB
```
