### ISSUE TITLE
AWX | Pass-through artefact information between forms

### ISSUE THREAD

**Issue by ronrem** [ansibleguy76/ansibleforms#118]
Hi,

I would like to extend my gratitude for the excellent application you have developed, and I appreciate the ongoing efforts to maintain its quality.

I am writing to inform you that I have successfully integrated Ansibleforms with our AWX environment, allowing me to create forms and launch AWX "Job Templates" seamlessly. At this juncture, I am eager to advance my form capabilities and simulate a "Workflow Job Template, by stitching multiple node and passing through artefacts."

I have encountered a specific challenge in this process:
Passing Job ID Information to the Next Form: When launching AWX "Job Templates" via Ansibleform, I am able to retrieve the job ID. However, I am keen to parse this information to the next form using the "onSuccess" event. Specifically, I aim to fetch the previous Artifact, and I understand that this information can be obtained through an AWX API query to "/api/v2/jobs/${job.id}." 

Could you guide me on the best approach to achieve this seamlessly?

I appreciate your time and assistance in addressing these inquiries.

Thank you once again for your exceptional work, and I look forward to your prompt response.
Best Regards,
Ronald

**Comment by ansibleguy76** [comment]
That's not implemented yet.
the form does accept a querystring, so let me see if I can grab the awx jobid and pass it to the next form.

**Comment by ansibleguy76** [comment]
in v4.0.20:
AnsibleForm jobid is exported as extravar as "__jobid__ " => you can then use it to store a tmp file file somewhere with information (you will have to do this in your playbook)

This same jobid will be passed to the next form as "__previous_jobid__" => you will have to make sure this field is available and it will be populated with the previous job id.  You can make this text field hidden (also new in v4.0.20)

**Comment by ansibleguy76** [comment]
something like :

```
  - name: __previous_jobid__
    label: Previous jobid
    type: text
    hide: true
  - name: previous_output
    type: expression
    expression: fn.fnReadYamlFile('.../tmp_output_$(__previous_jobid__)')
```

you will have to find your own logic to make sure awx is storing the output file so it's reachable from AF, a file, or a database, ...

**Comment by ronrem** [comment]
Awesome, this will be much of value to us! Will test this as soon as v4.0.20 becomes available.

**Comment by ansibleguy76** [comment]
Pushing now to beta... Would be helpfull if you are willing to test...  don't forget to put your image to ":beta" instead ":latest".
available in 10minutes

**Comment by ansibleguy76** [comment]
https://ansibleforms.com/faq/#pass-the-current-jobid
https://ansibleforms.com/form/#job-status-action-object

**Comment by ansibleguy76** [comment]
beta is ready

**Comment by ansibleguy76** [comment]
okay, let me check... 
1) that's why it's a beta
2) I have made a some extra error handling around the rest functions... Let's me test here internally.  I'll come back

**Comment by ronrem** [comment]
> okay, let me check...
> 
> 1. that's why it's a beta
> 2. I have made a some extra error handling around the rest functions... Let's me test here internally.  I'll come back

It's working, it mandatory now to have all fields.

**Comment by ansibleguy76** [comment]
I was just checking and indeed, it works fine here

**Comment by ansibleguy76** [comment]
type: awx
fields:
  - name: awx_server
    type: text
    default: 172.16.50.1
    hide: true
  - name: var1
    type: enum
    expression: fn.fnRestJwtSecure('get','https://$(awx_server)/api/v2/job_templates','','awx','[.results[]|.name]')

works fine on my end, and no, not all fields are mandatory...
Nothing has changed on the part.

**Comment by ronrem** [comment]
I think I'm really close, hopefully you can help me with the last step(s). I've have created a db table and a record, I'm trying to query the record.

Created the database on the mysqldb server:
```
USE AnsibleForms;
CREATE TABLE awx_mapping (
    af_id INT,
    awx_id INT,
    PRIMARY KEY (af_id, awx_id)
);
INSERT INTO awx_mapping (af_id, awx_id) VALUES
(68, 32137);
```

Create a credential configuration for my mysql connection:
```
mysql> SELECT * FROM credentials;
+----+-----------------+------------------------------+-----------------------------------------------------------------------------------------------+---------+------+-------------+--------+---------+--------------+-------------+
| id | name            | user                         | password                                                                                      | host    | port | description | secure | db_type | db_name      | is_database |
+----+-----------------+------------------------------+-----------------------------------------------------------------------------------------------+---------+------+-------------+--------+---------+--------------+-------------+
|  3 | mysql_user      | root                         | 59bbfab7124cf6c1181d2bd6ef83eea7.a94e88b074d4d3c27efb1e677c7ce9e7                             | mysqldb | 3306 |             |      0 | mysql   | AnsibleForms |           1 |
+----+-----------------+------------------------------+-----------------------------------------------------------------------------------------------+---------+------+-------------+--------+---------+--------------+-------------+
3 rows in set (0.00 sec)
```

Got the following forms configuration:
```
- name: awx_job_id
  type: enum
  dbConfig:
  name: mysql_user
  type: mysql
  query: select * from awx_mapping
```

But unfortunately I get the following error when launching the form:
```
'awx_job_id' has query errors
[mysql_user] query error : Error: No database selected
```

Enabled debugging, the logs only show the following lines:
```
2023-11-30 17:37:31:3731 info: [mysql][mysql_user] Running query select * from awx_mapping
2023-11-30 17:37:31:3731 debug: Finding credential mysql_user
2023-11-30 17:37:31:3731 debug: [mysql_user] query : select * from awx_mapping
2023-11-30 17:37:31:3731 debug: [mysql_user] connection found : mysql_user
```
What is missing in my configuration. 
Thanks again!

**Comment by ronrem** [comment]
Found it, the query was not clear to me, this was not mentioned in the documentation. Can you please confirm?
```
- name: awx_job_id
        type: enum
        dbConfig:
          name: mysql_user
          type: mysql
        query: select af_id, awx_id from AnsibleForms.awx_mapping
```

**Comment by ansibleguy76** [comment]
correct, I would suggest to create a second database (to not touch the AF database) and create a table in there.
when selecting from a table, one should always tell the database, either with USE or in the SELECT statement.

**Comment by ronrem** [comment]
Thanks, It seems that the AnsibleForms.job_output contains all needed information, and I'm querying the previous job-id, and narrow down the results with .regexBy({output:'.\*jobid.\*'}). The result of  Job-is is as follows:
```
Launched template AWX-Job-Template with jobid 31423
```
How to preform the regex jobid\s(\d+) so only the integer is return.
```
  fields:
    - name: __previous_jobid__
      label: Previous jobid
      type: text
      hide: false

    - name: awx_job_id
      type: expression
      dbConfig:
        name: mysql_user
        type: mysql
      query: select * from AnsibleForms.job_output where job_id = $(__previous_jobid__);

    - name: blabla
      type: expression
      expression: |
        fnArray.from($(awx_job_id))
        .regexBy({output:'.*jobid.*'})  
        .selectAttr({'output': 'output'})
      runLocal: true

    - name: Job-id
      type: text
      default: $(blabla[0].output)
```
My selectAttr statement is different than mentioned in the documentation, it only works as mentioned above. Can you please confirm?

And I'm not able to grap the job-id in the AWX launch form and save it to my database, can you give me a more detailed example? Thanks again for helping me out.
