### ISSUE TITLE
Modeling extravar with variable

### ISSUE THREAD

**Issue by ronrem** [ansibleguy76/ansibleforms#120]
I am currently modeling the output of my extravar and require the use of a variable as a key. Regrettably, the variable is being treated as a string.
```
  fields:
    - name: cve
      label: CVE indentifier
      type: text
      regex:
        expression: "^CVE-\\d{4}-\\d{4,7}$"
        description: Please define a correct CVE indentifier (eg CVE-1234-12345)
      model: $(cve).cve
      group: CVE information

    - name: cert_title
      label: CVE title
      type: text
      regex:
        expression: "^.*$"
        description: Please define the Cert CVE OCD indentifier (integer)
      model: $(cve).cert_title
      group: CVE information
```
resulting in the following output:
```
"$(cve)":
  {
    "cve": "CVE-1111-11111",
    "cert_title": "My first CVE creation"
  }
```
I'm expecting:
```
"CVE-1111-11111":
  {
    "cve": "CVE-1111-11111",
    "cert_title": "My first CVE creation"
  }
```
