### ISSUE TITLE
Consume django rest framework  data for enum expressions (netbox integration)

### ISSUE THREAD

**Issue by MalfuncEddie** [ansibleguy76/ansibleforms#122]
**Is your feature request related to a problem? Please describe.**

I'm trying to ducktape netbox  (https://github.com/netbox-community/netbox) together with ansible forms. A lot of my automation data is stored in netbox. 

- Currently (I think) only username/password are supported as credential but netbox uses a token based approach. (https://demo.netbox.dev/static/docs/rest-api/authentication/)
- The results are situated in in the results array and is not a flat object?

```
{
    "count": 101,
    "next": "https://netbox/api/tenancy/tenants/?limit=100&offset=100",
    "previous": null,
    "results": [
        {
            "id": 73,
            "name": "tenantA"
...
           
```

**Describe the solution you'd like**

It would be a great improvement if token based authentication could be used. and you can select what field you need  and value

eg:

Get every "name" of "results" in the dropdown.
 

Netbox has a great api that can be used and it would be nice if ansible forms can integrate with netbox since it does have an hierarchy (region -> site- > ...).
Example:

dropdown select tenant
if tenant is selected the 2nd drop down shows only the sites of the tenant. 
https://netbox/api/dcim/sites/?tenant=(field from dropdown 1)

**Describe alternatives you've considered**
Still figuring this project out so could be I just missed things in the documentation :)

alternative: dump the api fields to json every night and use json files?
alternative2: user custom scripts in netbox but that does not have the features rich features of this project 

**Additional context**
I really like this project since it fills in a gap left by the awx team, but Javascript front end / typescript is an unexplored field for me ;(

**Comment by ansibleguy76** [comment]
why not using advanced directly. why the wrap?

**Comment by ansibleguy76** [comment]
> ugly hack in default.js
> 
> ```
> exports.fnRestNetbox = async function (action, url, body, token, jqe = null, sort = null, hasBigInt = false) {
>   var headers = {}
>   if (token) {
>     headers.Authorization = "Token censored"
>   }
>   return await exports.fnRestAdvanced(action, url, body, headers, jqe, sort, hasBigInt)
> }
> ```

Just use fn.fnRestAdvanced twice (post => token => get with headers)

No need to for the "if (token)".

**Comment by MalfuncEddie** [comment]
```
name: test form
type: awx
template: template tst
description: ""
roles:
  - admin
categories: []
tileClass: has-background-info-light
icon: bullseye
fields:
  - type: enum
    name: Tenant
    expression: fn.fnRestAdvanced( 'get', 'https://netbox/api/tenancy/tenants/','',{ 'Authorization':'Token aaaaaaaaaaaaaaaaa'}, '[.results[]]')
    columns:
      - name
    valueColumn: id
```

Thanks for the info. I got it working. Only issue i have is that I would have liked the "aaaaaaaa" token to come from a ansible forms credential but not sure if fnRestAdvanced supports that. either case it is a read only credential so no big woop :)
