### ISSUE TITLE
change default number field value depending of a radio field.

### ISSUE THREAD

**Issue by ansibleguy76** [ansibleguy76/ansibleforms#132]
### Discussed in https://github.com/ansibleguy76/ansibleforms/discussions/131

<div type='discussions-op-text'>

<sup>Originally posted by **revolonl** January  4, 2024</sup>
Hello,
i have a Radio field (Small-Medium-Large). I want to set a number field with a number depending of the radio choice (2 if small is selectected, 4 if it's Medium and 8 if it's large)
Is it possible, and how ?

Thanks.</div>

**Comment by ansibleguy76** [comment]
5.0.0 (latest beta), now supports an array of objects with label/value properties.

```
values:
- label: Red
  code: ff0000
- label: Green
  code: 00ff00
- label: Blue
  code: 0000ff
```
