### ISSUE TITLE
Add __instance_groups__ to allow to launch a job template with a instance_groups parameter

### ISSUE THREAD

**Issue by MalfuncEddie** [ansibleguy76/ansibleforms#136]
**Is your feature request related to a problem? Please describe.**
https://docs.ansible.com/ansible/latest/collections/awx/awx/job_launch_module.html#parameter-instance_groups

In recent awx deployments you can select the instance group at joblaunch (if promp instance groups is active). It would be nice if extra var `__instance_groups__` can be translated to an instance group list 

**Describe alternatives you've considered**
An awx template per instance group (like the old versions of AWX where this is not possible)

**Comment by ansibleguy76** [comment]
will be added to 5.0.0 (still beta).  Expect a build in 15 minutes.
Let me know if it all works.

**Comment by ansibleguy76** [comment]
it will be __instanceGroups__ as field or instanceGroups (on form level)

**Comment by ansibleguy76** [comment]
I have no recent AWX to test it

**Comment by MalfuncEddie** [comment]
form:

```
- name: igtest
  type: awx
  template: Gather_Facts_Custom
  description: ""
  roles:
    - admin
  categories:
    - Default
  tileClass: has-background-info-light
  icon: fa-brands fa-linux
  fields:
    - name: __instanceGroups__ 
      type: enum
      multiple: true
      values:
        - "IGA"
        - "IGB"
```

```
instance_groups:
  - Incorrect type. Expected pk value, received str.
failed to launch awx template Gather_Facts_Custom 2024-01-18 20:37:07
failed to launch Gather_Facts_Custom
instance_groups:
  - Incorrect type. Expected pk value, received str.
```

Is the code in the devop branch then I can take a look :)

(when looking at a job that has been launched in awx with the ask instance group --> this is added) 

```
        "instance_group": {
            "id": 7,
            "name": "IGB",
            "is_container_group": false
        },
```
