### ISSUE TITLE
Role assignment with ldap user no longer works

### ISSUE THREAD

**Issue by Angmar3019** [ansibleguy76/ansibleforms#264]
**Role assignment with ldap user no longer works**
First of all, thank you very much for the project, I'm really enjoying it.

I have connected my ansible forms to an Active Directory and use authentication via ldap. Everything is set up correctly and has worked since then, or is still working to some extent.

The problem I have now, which I suspect occurred with version v.5.0.8, is that I can no longer assign ldap users to the forms roles. Ldap roles still work without any problems. Maybe it has something to do with the new role options that were added with v5.0.8.

I verified the role assignment with the “About me” tab and whether you can see the admin interface. I also considered that roles are only applied after logging out and in again.

**To Reproduce**
To explain, we assume that there is a ldap user `user@domain.com` and that this user is in the group `groups`.
For the form configuration, we would then call the two with `ldap/user@domain.com` and `ldap/groups`.

This is my exemplary existing configuration, where I have assigned only the user to two forms groups. Previously, the user was assigned all three roles, but now he only has the role `public` assigned. 
```
roles:
  - name: example
     users:
       - ldap/user@domain.com
  - name: admin
    groups:
      - local/admins
    users:
      - ldap/user@domain.com
  - name: public
     groups: []  
```
<br>

If you switch the mapping for debug reasons to roles only, as shown below, then the mapping works again without any problems and the user is assigned all three roles.
```
roles:
  - name: example
     groups:
       - ldap/groups
  - name: admin
    groups:
      - local/admins
      - ldap/groups
  - name: public
     groups: []  
```
<br>

If we combine both approaches as in the example below, the user only gets the roles `example` and `public`, but not `admin`.
```
roles:
  - name: example
     groups:
       - ldap/groups
  - name: admin
    groups:
      - local/admins
    users:
      - ldap/user@domain.com
  - name: public
     groups: []  
```

**Expected behavior**
Assigning roles based on ldap users has worked since then and with ldap roles it still works, hence my assumption that it is a bug. Many thanks for your help.

**Version**
ansibleforms v5.0.8
