### ISSUE TITLE
Restrict LDAP login to group

### ISSUE THREAD

**Issue by jahovi** [ansibleguy76/ansibleforms#285]
First of all, thank you very much for this project, I love it.

**Is your feature request related to a problem? Please describe.**
The problem is that I would like to use LDAP authentication but only allow members of a certain LDAP group to login.

**Describe the solution you'd like**
In Tower/AWX there is an option called "LDAP Require Group" that takes the DN of a group and does exactly what I need: When a user matches the search base, they are allowed to login, but only if they are also a member of the specified group. When the option is not set, everyone in LDAP that matches the search base is able to login.

I would appreciate it very much if Ansible Forms offered an option similar to "LDAP Require Group" as described above.

**Comment by ansibleguy76** [comment]
I don't like just a single group... it's like too limited and that doesn't work for every login or future logins.  But my login procedure is always like this : 

- you authenticate, 
- you get your groups 
- and then based on groups or user you get assigned certain roles (using the forms.yaml).  

What if I would allow an env var that allows a regex pattern for require login role ?  You can make as many roles based on groups & users.  You could make an "af_login"-role, and with the pattern I could allow a login.  The login role pattern would default to ".*"

**Comment by ansibleguy76** [comment]
![Image](https://github.com/user-attachments/assets/39e2e71e-6895-471a-b8bb-d60a7f158972)

```
- name: admin
  groups:
    - local/admins
    - ldap/Domain Admins
    - oidc/default-roles-ansibleforms
  options:
    extendedTokenExpiration: true
    enableLogin: true
- name: operator
  groups:
    - local/operators
  options:
    showDesigner: true
    showLogs: true
    showSettings: true
    showDebugButtons: true
    enableLogin: true
- name: demo
  groups:
    - local/demo
- name: test
  users:
    - ldap/btom
  options:
    showAllJobLogs: true
    enableLogin: true
- name: public
  groups: []
  options:
    enableLogin: false
```

will be available in latest beta (5.0.10).  Hoping to hear some feedback

![Image](https://github.com/user-attachments/assets/b689ce61-92a4-4e91-b531-c59a7ccebac9)
