### ISSUE TITLE
Tablefields: Allow enum multiple selection

### ISSUE THREAD

**Issue by Angmar3019** [ansibleguy76/ansibleforms#289]
**Is your feature request related to a problem? Please describe.**
If you set the attribute “mutliple” to true for enum fields in a tablefield, then this is not allowed and ansibleforms says the form is invalid.

**Describe the solution you'd like**
If I allow “multiple” selection, it should be possible to select several values in the table, as with the normal enum fields. When several values have been selected, these should be saved as normal in an array, then in the table in a nested array.

**Describe alternatives you've considered**
-

**Additional context**
Working with single selection:
```
- name: table
  type: table
  tableFields:
   - name: Enum
     label: Enum
     type: enum
     values:
      - 1
      - 2
      - 3
```
Should be allowed:
```
- name: table
  type: table
  tableFields:
   - name: Enum
     label: Enum
     type: enum
     multiple: true
     values:
      - 1
      - 2
      - 3
```
