### ISSUE TITLE
How can I extract the response headers from a fnRestAdvanced expression?

### ISSUE THREAD

**Issue by ansibleguy76** [ansibleguy76/ansibleforms#297]
### Discussed in https://github.com/ansibleguy76/ansibleforms/discussions/296

<div type='discussions-op-text'>

<sup>Originally posted by **nikos445** June  5, 2025</sup>
I am trying to extract the response.headers (X-Subject-Token) from a fnRestAdvanced request. Is this possible?</div>

**Comment by ansibleguy76** [comment]
So I extended fnAdvancedRest :

you use the following 3 placeholders in headers:
base64(name_of_credential) => this way, you can securily get credentials from the vault, use like "basic base64(my_cred)"
username(name_of_credential) => will replace with username
password(name_of_credential) => will replace with password

it has a new option "raw" parameter that will return both data & response_headers.

```
fields:
  - type: expression
    name: test_advanced
    label: advanced_data
    expression: fn.fnRestAdvanced('post','https://172.16.50.4:3000/api/v1/auth/login',{},{'Authorization':'basic base64(localrest)'},null,null,false,true)
```

added in 5.0.10
